# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbm < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/dewey/tbm"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dewey/tbm/releases/download/v0.0.5/tbm_0.0.5_Darwin_arm64.tar.gz"
      sha256 "4efd0a860fa2be8a28a3a78c2b59c3719858a10731db27fa90b343a1eff56da0"

      def install
        bin.install "tbm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dewey/tbm/releases/download/v0.0.5/tbm_0.0.5_Linux_arm64.tar.gz"
      sha256 "53a96631abfe4fda778ddfffa68e0cede91c6797cc2698e490ab46ab574b6b4d"

      def install
        bin.install "tbm"
      end
    end
  end
end
