# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbm < Formula
  desc "A simple way to start multiple services like cloud-sql-proxy, IAP proxy, kubefwd or any other command really at once and keep them running in the background."
  homepage "https://github.com/dewey/tbm"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dewey/tbm/releases/download/v0.0.7/tbm_0.0.7_darwin_arm64.tar.gz"
      sha256 "e6261f0b91e9e89005fe9fa4d15d57bb2e4a0f0caf329ae77f68d5a7904195ff"

      def install
        bin.install "tbm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dewey/tbm/releases/download/v0.0.7/tbm_0.0.7_darwin_amd64.tar.gz"
      sha256 "2d76aa385eafbbbf35ab2ae87c1eebfca84db8ca458cbeebdfc654d547a511d6"

      def install
        bin.install "tbm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dewey/tbm/releases/download/v0.0.7/tbm_0.0.7_linux_arm64.tar.gz"
      sha256 "161cfaa94a1a10f53094e405214b549dc23b68f7915241c4c786ac2314fb3641"

      def install
        bin.install "tbm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dewey/tbm/releases/download/v0.0.7/tbm_0.0.7_linux_amd64.tar.gz"
      sha256 "68aebe155d14810c75775e174e9d4f31ef366f5e520c9cab1d1f34af86c520c9"

      def install
        bin.install "tbm"
      end
    end
  end
end
