# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbm < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/dewey/tbm"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dewey/tbm/releases/download/v0.0.3/tbm_0.0.3_Darwin_arm64.tar.gz"
      sha256 "a356619382f34fae7d4537dd30eeecba15c0ab34ad9aacb4e7481549d14ae661"

      def install
        bin.install "tbm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dewey/tbm/releases/download/v0.0.3/tbm_0.0.3_Linux_arm64.tar.gz"
      sha256 "d49c40a59157849feaffa646b0600b9d2017d874358c63cbcfc4a64f77b6da02"

      def install
        bin.install "tbm"
      end
    end
  end
end
