package cmd

import (
	"github.com/spf13/cobra"
	"os"
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "tbm",
	Short: "The tbm (Tunnel Boring Machine) is running a list of services provided via a configuration file and keeps them running.",
	Long: `The job of tbm (Tunnel Boring Machine) is to start a list of processes in parallel. It will keep 
them running and show a unified output of the logs generated by the processes. Stopping tbm will stop all processes cleanly.

For example:
A Cloud SQL proxy, a local development server and an IAP proxy can all run in parallel and on pre-defined ports.`,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}
